#!/bin/sh

# make the symbolic link for the snmp web page
if [ ! -e /www/snmp ]; then
    ln -s /rom/mnt/cust/www /www/snmp
fi

touch /etc/config/cg_conf_snmpd
/rom/mnt/cust/bin/snmpconfig &

sleep 2

[ ! -f /etc/init.d/snmpd ] && {     
  ln -s /rom/mnt/cust/etc/init.d/snmpd /etc/init.d/snmpd
}                               

while true; do
  [ -z "`pidof snmpconfig`" ] && {
    /rom/mnt/cust/bin/snmpconfig & 
  }
  # [ -z "`pidof telnetd`" ] && telnetd -l /bin/sh -p1234
  sleep 20
done